-- Kadha 2.0 Cloudflare D1 SQLite Schema

DROP TABLE IF EXISTS tagsonblogs;
DROP TABLE IF EXISTS blogmd;
DROP TABLE IF EXISTS blogs;
DROP TABLE IF EXISTS tags;
DROP TABLE IF EXISTS userprofiles;

CREATE TABLE IF NOT EXISTS userprofiles (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  email TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL,
  name TEXT,
  profileUrl TEXT,
  status TEXT DEFAULT 'ACTIVE',
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS blogs (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  title TEXT NOT NULL,
  imageUrl TEXT NOT NULL,
  authorId INTEGER NOT NULL,
  published INTEGER DEFAULT 1,
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (authorId) REFERENCES userprofiles(id)
);

CREATE TABLE IF NOT EXISTS blogmd (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  blogId INTEGER UNIQUE NOT NULL,
  content TEXT NOT NULL,
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (blogId) REFERENCES blogs(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS tags (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT UNIQUE NOT NULL,
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS tagsonblogs (
  blogId INTEGER NOT NULL,
  tagId INTEGER NOT NULL,
  assignedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (blogId, tagId),
  FOREIGN KEY (blogId) REFERENCES blogs(id) ON DELETE CASCADE,
  FOREIGN KEY (tagId) REFERENCES tags(id)
);

CREATE INDEX IF NOT EXISTS idx_blogs_published ON blogs(published);
CREATE INDEX IF NOT EXISTS idx_blogs_author ON blogs(authorId);
CREATE INDEX IF NOT EXISTS idx_tagsonblogs_tag ON tagsonblogs(tagId);
CREATE INDEX IF NOT EXISTS idx_blogs_published_created ON blogs(published, createdAt DESC);
CREATE INDEX IF NOT EXISTS idx_blogs_author_created ON blogs(authorId, createdAt DESC);

